### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by TechnologyClassroom** [argosopentech/argospm-index#1]
Would the code in this repository be the same as [argos-translate](https://github.com/argosopentech/argos-translate)?  If so, would you like me to make a PR to add license information to this repository?

argos-translate license information:

## License
Dual licensed under either the [MIT License](https://github.com/argosopentech/argos-translate/blob/master/LICENSE) or [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/).

**Comment by PJ-Finlay** [comment]
Yes all Argos Repositories are intended to be licensed under either MIT or CC0. A pull request would be appreciated.
